### ISSUE TITLE
USPS Proxy includes pry

### ISSUE THREAD

**Issue by sashax** [18F/usps-proxy#6]
This is not kosher! Please fix.

https://github.com/18F/usps-proxy/blob/master/lib/usps-proxy.rb#L11

**Comment by monfresh** [comment]
`dotenv` should not be required either, and should not be a runtime dependency. Users of this gem should be able to point to an ENV var however they want. Furthermore, this gem provides a way to set the USPS username via an initializer which doesn't require dotenv.

**Comment by amoose** [comment]
Resolved with #7
